SRC		:= src/builtins/padloper_cd.c \
src/builtins/padloper_echo.c \
src/builtins/padloper_env.c \
src/builtins/padloper_exit.c \
src/builtins/padloper_export.c \
src/builtins/padloper_pwd.c \
src/builtins/padloper_unset.c \
src/error/error.c \
src/executer/error_handling.c \
src/executer/executer.c \
src/executer/executer_utils.c \
src/executer/file_handling.c \
src/executer/heredoc_handling.c \
src/executer/list_sim.c \
src/executer/path_builder.c \
src/lexer/charchecks.c \
src/lexer/fsm_op.c \
src/lexer/fsm_op2.c \
src/lexer/lexer.c \
src/lexer/stx_error.c \
src/main.c \
src/parcer/expand.c \
src/parcer/expand2.c \
src/parcer/parcer.c \
src/parcer/separate.c \
src/parcer/separation_utils.c \
src/parcer/simple_cmd.c \
src/parcer/stitching.c \
src/tests/tests.c \
src/utils/filelst_utils.c \
src/utils/simple_cmd_utils.c \
src/utils/token_section_utils.c \
src/utils/token_section_utils2.c \
src/utils/token_utils.c \
src/utils/token_utils2.c \

HDR		:= src/error/error.h \
src/executer/executer.h \
src/hdr/structs.h \
src/lexer/hdr/charchecks.h \
src/lexer/hdr/errors.h \
src/lexer/hdr/fsm.h \
src/lexer/hdr/lexer.h \
src/parcer/hdr/expand.h \
src/parcer/hdr/parcer.h \
src/parcer/hdr/separate.h \
src/tests/tests.h \
src/utils/hdr/filelst_utils.h \
src/utils/hdr/simple_cmd_utils.h \
src/utils/hdr/token_utils.h \
